import { COLORS } from "@/utils/colors";
import { Box, Container } from "@mui/material";
import FiberForm from "@/components/form";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web Development Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          backgroundColor: COLORS.GREY,
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Container
          maxWidth="sm"
          sx={{
            margin: "auto",
            boxShadow:
              "rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px",
            p: 3,
            borderRadius: 3,
            backgroundColor: COLORS.WHITE,
          }}
        >
          <FiberForm />
        </Container>
      </Box>
    </>
  );
}
